# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, nixpkgs, ... }:

{
  imports =
    [
      "${nixpkgs}/nixos/modules/profiles/qemu-guest.nix"
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/152d6ed6-f14f-4e99-a42c-30b61cfe46c2";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/01d0f985-a53e-4153-96c7-3020611450c6";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/eec757aa-4fad-4bb4-b471-ad9ace55b9bb"; }];

  nix.maxJobs = lib.mkDefault 8;
}
